"""
ansi - Native module
"""

from typing import Any, Callable, Iterable, Iterator, List, Optional, TypeVar, Union

def reset() -> str: ...
def fg(value: Union[str, int]) -> str:
    """
    color can be: name ("red"), hex ("#ff5500"), or int (0-255)
    """
    ...

def bg(value: Union[str, int]) -> str: ...
def rgb(r: int, g: int, b: int, bg: bool = False) -> str: ...
def bold() -> str:
    """
    Style Functions
    """
    ...

def dim() -> str: ...
def italic() -> str: ...
def underline() -> str: ...
def blink() -> str: ...
def reverse() -> str: ...
def hidden() -> str: ...
def strikethrough() -> str: ...
