"""
input - Native interactive input module for ucharm
"""

from typing import Any, Callable, Iterable, Iterator, List, Optional, TypeVar

def confirm(prompt: str, *, default: bool = True) -> bool: ...
def select(prompt: str, choices: List[str], default: int = 0) -> Optional[str]: ...
def multiselect(
    prompt: str, choices: List[str], defaults: Optional[List[str]] = None
) -> List[str]: ...
def prompt(message: str, default: Optional[str] = None) -> str: ...
def password(message: str) -> str: ...
