"""
args - Native module
"""

from typing import Any, Callable, Dict, Iterable, Iterator, List, Optional, TypeVar

def raw() -> List[str]: ...
def get(index: int, default: Optional[Any] = None) -> Optional[str]: ...
def count() -> int: ...
def has(flag: str) -> bool: ...
def value(flag: str, default: Optional[Any] = None) -> Optional[str]: ...
def int_value(flag: str, default: int = 0) -> int: ...
def positional() -> List[str]: ...
def parse(spec: Dict[str, Any]) -> Dict[str, Any]: ...
