"""
term - Native module
"""

from typing import Any, Callable, Iterable, Iterator, List, Optional, Tuple, TypeVar

def size() -> Tuple[int, int]: ...
def raw_mode(value: bool) -> None: ...
def read_key() -> Optional[str]: ...
def cursor_pos(x: int, y: int) -> None: ...
def cursor_up(n: int = 1) -> None: ...
def cursor_down(n: int = 1) -> None: ...
def cursor_left(n: int = 1) -> None: ...
def cursor_right(n: int = 1) -> None: ...
def clear() -> None: ...
def clear_line() -> None: ...
def hide_cursor() -> None: ...
def show_cursor() -> None: ...
def is_tty() -> bool: ...
def write(text: str) -> None: ...
